/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Dao.VillageChieDao;
import Model.CellChief;
import Model.VillageChief;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Divin
 */
public class VillageChiefManagement extends javax.swing.JFrame {
                private CellChief cellChief;
    /**
     * Creates new form VillageChiefManagementForm1
     */
    public VillageChiefManagement(CellChief cellChief) {
        this.cellChief = cellChief;
        initComponents();
        loadVillageChiefs();
    }
    private void loadVillageChiefs() {
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel(); // ✅ Get the table model
model.setRowCount(0); // ✅ Clear the table
VillageChieDao villageChiefDao = new VillageChieDao();
try{
List<VillageChief> villageChiefs = villageChiefDao.getAllVillageChiefs(cellChief.getId());
for (VillageChief villageChief : villageChiefs) {
    Object[] row = {
        villageChief.getId(),
        villageChief.getFullName(),
        villageChief.getNationalId(),
        villageChief.getVillageName(),
        villageChief.getPhoneNumber()
    };
    model.addRow(row); // ✅ Use model, not jTable1
}
}
catch(SQLException ex){
         JOptionPane.showMessageDialog(this, "Failed to load village chiefs: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
}
    }
    private void clearFields() {
    fullNameField.setText("");
    nationalIdField.setText("");
    villageNameField.setText("");
    phoneNumberField.setText("");

    fullNameField.requestFocus();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fullNameField = new javax.swing.JTextField();
        nationalIdField = new javax.swing.JTextField();
        villageNameField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Umuganda Management System");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/log3-removebg-preview.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("National ID (16 Digits):");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Village Name:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone(07xxxxxxxx):");

        phoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberFieldActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("TASKS");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton6.setText("REPORT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Full Name", "National ID", "Village Name", "Phone Number"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(villageNameField)
                                    .addComponent(fullNameField)
                                    .addComponent(nationalIdField)
                                    .addComponent(phoneNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))))
                        .addGap(78, 78, 78)
                        .addComponent(jButton6)))
                .addGap(76, 79, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(65, 65, 65)
                        .addComponent(jButton2)
                        .addGap(51, 51, 51)
                        .addComponent(jButton3)
                        .addGap(66, 66, 66)
                        .addComponent(jButton4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(nationalIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(villageNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(37, 37, 37)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void phoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fullName = fullNameField.getText().trim();
        String nationalId = nationalIdField.getText().trim();
        String villageName = villageNameField.getText().trim();
        String phoneNumber = phoneNumberField.getText().trim();
        
        // Validation
        if (fullName.isEmpty() || nationalId.isEmpty() || villageName.isEmpty() || phoneNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (nationalId.length() != 16 || !nationalId.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "National ID must be 16 digits", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
       if (
    !(phoneNumber.startsWith("078") || phoneNumber.startsWith("079") ||
      phoneNumber.startsWith("072") || phoneNumber.startsWith("073")) ||
    phoneNumber.length() != 10 ||
    !phoneNumber.matches("\\d+")
)
{
            JOptionPane.showMessageDialog(this, "Phone number must start with 078 or 079 or 073 or 072  and be 10 digits", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            VillageChieDao villageChiefDao = new VillageChieDao();
            
            if (villageChiefDao.nationalIdExists(nationalId)) {
                JOptionPane.showMessageDialog(this, "National ID already exists", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            if (villageChiefDao.villageNameExists(villageName)) {
                JOptionPane.showMessageDialog(this, "Village name already exists", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            VillageChief villageChief = new VillageChief(fullName, nationalId, villageName, phoneNumber, cellChief.getId());
            
            if (villageChiefDao.registerVillageChief(villageChief)) {
                
                clearFields();
                loadVillageChiefs();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add village chief", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a village chief to update", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int villageChiefId = (int) jTable1.getValueAt(selectedRow, 0);
        String fullName = fullNameField.getText().trim();
        String nationalId = nationalIdField.getText().trim();
        String villageName = villageNameField.getText().trim();
        String phoneNumber = phoneNumberField.getText().trim();
        
        // Validation
        if (fullName.isEmpty() || nationalId.isEmpty() || villageName.isEmpty() || phoneNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (nationalId.length() != 16 || !nationalId.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "National ID must be 16 digits", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!phoneNumber.startsWith("07") || phoneNumber.length() != 10 || !phoneNumber.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Phone number must start with 07 and be 10 digits", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            VillageChieDao villageChiefDao = new VillageChieDao();
            VillageChief currentVillageChief = villageChiefDao.getVillageChiefById(villageChiefId);
             boolean isDataChanged = false;

        if (currentVillageChief != null) {
            // Compare each field and check if any value has changed
            if (!currentVillageChief.getFullName().equals(fullName)) {
                isDataChanged = true;
            }
            if (!currentVillageChief.getNationalId().equals(nationalId)) {
                isDataChanged = true;
            }
            if (!currentVillageChief.getVillageName().equals(villageName)) {
                isDataChanged = true;
            }
            if (!currentVillageChief.getPhoneNumber().equals(phoneNumber)) {
                isDataChanged = true;
            }
        }

                if (!isDataChanged) {
            JOptionPane.showMessageDialog(this, "No changes were made", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
                // Check if national ID is being changed to one that already exists

                if (currentVillageChief != null && !currentVillageChief.getNationalId().equals(nationalId)) {
                    if (villageChiefDao.nationalIdExists(nationalId)) {
                        JOptionPane.showMessageDialog(this, "National ID already exists", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }

                // Check if village name is being changed to one that already exists
                if (currentVillageChief != null && !currentVillageChief.getVillageName().equals(villageName)) {
                    if (villageChiefDao.villageNameExists(villageName)) {
                        JOptionPane.showMessageDialog(this, "Village name already exists", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
            
            VillageChief villageChief = new VillageChief(fullName, nationalId, villageName, phoneNumber, cellChief.getId());
            villageChief.setId(villageChiefId);
            
            if (villageChiefDao.updateVillageChief(villageChief)) {
                JOptionPane.showMessageDialog(this, "Village chief updated successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                clearFields();
                loadVillageChiefs();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update village chief", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         // Get the selected row index
    int selectedRow = jTable1.getSelectedRow();
    
    // If no row is selected, return
    if (selectedRow < 0) {
        return;
    }
    
    // Get data from the selected row (assuming the first column is the ID)
    int villageChiefId = (int) jTable1.getValueAt(selectedRow, 0);
    String fullName = (String) jTable1.getValueAt(selectedRow, 1);
    String nationalId = (String) jTable1.getValueAt(selectedRow, 2);
    String villageName = (String) jTable1.getValueAt(selectedRow, 3);
    String phoneNumber = (String) jTable1.getValueAt(selectedRow, 4);
    
    // Set the data to the input fields (use setText for text fields)
    fullNameField.setText(fullName);
    nationalIdField.setText(nationalId);
    villageNameField.setText(villageName);
    phoneNumberField.setText(phoneNumber);
    
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a village chief to delete", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        int villageChiefId = (int) jTable1.getValueAt(selectedRow, 0);
        
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Are you sure you want to delete this village chief?", 
                "Confirm Delete", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                VillageChieDao villageChiefDao = new VillageChieDao();
                
                if (villageChiefDao.deleteVillageChief(villageChiefId)) {
                    JOptionPane.showMessageDialog(this, "Village chief deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    clearFields();
                    loadVillageChiefs();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete village chief", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
                new ReportForm1(cellChief).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        new TaskManagementForm1(cellChief, WIDTH).setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fullNameField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nationalIdField;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JTextField villageNameField;
    // End of variables declaration//GEN-END:variables
}
